apiVersion: v1
kind: Pod
metadata:
  name: bastion
  labels:
      version: v0.1
      kubernetes.io/cluster-service: "true"

spec:
  containers:
  - name: bastion
    image: quay.io/ipedrazas/alpine:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: Always
  restartPolicy: Always
  imagePullSecrets:
    - name: watchmaker-token-9yjo3
