apiVersion: v1
kind: Service
metadata:
  name: watchmaker
  labels:
    name: watchmaker
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: watchmaker
